### PR TITLE
Enhance recurrence

### PR DESCRIPTION
**Pull request by zeekoe**
Enhance recurrence support for my use cases

### CODE REVIEW

**Comment by zeekoe** [comment]
This builds on the "Desktop browser" PR.

**Comment by zeekoe** [comment]
Some more explanation:
Either nextcloud, or my Davx5 Android client:
* Usually creates recurring events without an 'until' date, but with 'count' filled in.
* Sometimes (at least one time) enters an event without and end date. This was dropped because of a null pointer somewhere.
* Enters biweekly events as weekly, interval 2.

These are now all supported.

BTW, what do you think of moving the recurrence / event view filtering to a central location? Now it's duplicated between event slider + rrule_check for styling the calendar cells.

Perhaps todo:
* Sometimes (at least one time) an incorrect start date is set for a recurring event. Currently this one event is shown in Mondays instead of Tuesdays. Fixing is possible by moving to the correct weekday, but it can also be considered as bad client behaviour...

**Comment by strukturart** [comment]
The rrule check can be executed in a function so that it can be used by the slider and cell styling.

**Comment by zeekoe** [comment]
Thanks. I might implement that, but wanted to ask in case there was a compelling reason. Thanks also for accepting my PR!

**Comment by strukturart** [comment]
check out -> https://github.com/strukturart/greg/tree/rrule_check

**Comment by strukturart** [comment]
Determining an end date should possibly be in the parser

https://github.com/strukturart/greg/blob/d19d0912620b42e77e03c01c64ac3918015de1d9/application/app.js#L1150
--->
https://github.com/strukturart/greg/blob/d19d0912620b42e77e03c01c64ac3918015de1d9/application/sw.js#L91

**Comment by zeekoe** [comment]
Yes indeed, I had the same thought while pondering this later on. :)

**Comment by strukturart** [comment]
@zeekoe see if .count still works for you, I have now moved the determination of the end date to the service worker

https://github.com/strukturart/greg/blob/1575a32ffe5ca90d78d40613e917a9f3f54aa392/application/sw.js#L101

**Comment by zeekoe** [comment]
Thanks! Sorry for the slow response; time flew... Several small things were broken... PR is on it's way.

**Comment by strukturart** [comment]
please checkout https://github.com/strukturart/greg/tree/cacheCalDavData 
it is the latest version and will soon be merged into the master branch. I now cache the parsed data, which speeds up starting the app.

**Comment by zeekoe** [comment]
Thanks, I might be able to try... Could you tell me what versions of node/npm/parcel you use? I can't use the app on my phone now because of probably some problem in a dependency. :(

**Comment by strukturart** [comment]
what happens when you type npm install?

**Comment by zeekoe** [comment]
Hmm, it seems to work, after I remove node_modules and .parcel_cache, then run npm install, then build.sh.

So I'm one step further. The error is somewhere in tsdav; normalizeName seems to be called on a header value instead of a header field, and then crashes on here:

`throw new TypeError("Invalid character in header field name");`

And apparently Nextcloud's header values are problematic. Well then. I think I'll keep using the built-in gaiamobile calendar; I hoped to get Greg working soon but it's too much of a hassle for now and apparently Nextcloud is too much different from Google calendar.

Thanks for all your help in trying to get it work! I might come back and have another try at some moment. :)
Oh and BTW, also thanks very much for o.map, I'm happily using that!

**Comment by strukturart** [comment]
Yes, I see there is a problem when logging in to nextcloud accounts, if you still feel like it you can install the current version, you should get an error message in the console if the login was not successful.

**Pull request merged**
